export const actionName = () => {
  return {
    type: 'ACTION_NAME'
    // other
  }
}


'ADD_CARDS' // BUILD DECK AFTER SEARCHING
'TOGGLE_LIKE' // TOGGLE LIKE OR DISLIKE ON EACH CARD
'CHANGE_VIEW' // BETWEEN ALL OUR COMPONENT VIEWS
'CHANGE_CARD' // BETWEEN ALL OUR CARDS INSIDE OUR DECK